# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
  mode: quick
  async: true
  create-group: true
  solc: 0.8.00
  remappings:
    - "@openzeppelin=node_modules/@openzeppelin"
